apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-backup-diff-region
spec:
  volumeSnapshotClassName: csi-gcp-filestore-backup-snap-class-diff-region
  source:
    persistentVolumeClaimName: test-pvc
