apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v2.2.2"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resize-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-resizer
  newTag: "v1.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-snapshotter
  newTag: "v4.1.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar-prow-rc
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.2.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-fs-driver-rc
imageTag:
  name: k8s.gcr.io/cloud-provider-gcp/gcp-filestore-csi-driver
  newName: gcr.io/k8s-staging-cloud-provider-gcp/gcp-filestore-csi-driver
  newTag: "v0.5.0-rc2"
---
