apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner-prow
imageTag:
  name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: "v3.4.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resize-prow
imageTag:
  name: registry.k8s.io/sig-storage/csi-resizer
  newTag: "v1.7.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter-prow
imageTag:
  name: registry.k8s.io/sig-storage/csi-snapshotter
  newTag: "v6.1.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar-prow
imageTag:
  name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.7.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gce-fs-driver
imageTag:
  name: registry.k8s.io/cloud-provider-gcp/gcp-filestore-csi-driver
  newTag: "v1.6.13"
---
